-- Base de Datos:
CREATE DATABASE IF NOT EXISTS finanzas_js;
USE finanzas_js;

-- Tablas:
CREATE TABLE IF NOT EXISTS tipos_gasto(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	tipo TEXT NOT NULL,
	descripcion TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS tipos_ingreso(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	tipo TEXT NOT NULL,
	descripcion TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS concepto_gastos(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	concepto TEXT NOT NULL,
	descripcion TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS concepto_ingresos(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	concepto TEXT NOT NULL,
	descripcion TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS gastos(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	tipo INT NOT NULL,
	concepto INT NOT NULL,
	monto DECIMAL(13, 2) NOT NULL,
	fecha DATE NOT NULL DEFAULT(CURRENT_DATE)
);
CREATE TABLE IF NOT EXISTS ingresos(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	tipo INT NOT NULL,
	concepto INT NOT NULL,
	monto DECIMAL(13, 2) NOT NULL,
	fecha DATE NOT NULL DEFAULT(CURRENT_DATE)
);
CREATE TABLE IF NOT EXISTS presupuestos(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	titulo TEXT NOT NULL,
	descripcion TEXT NOT NULL,
	fecha_inicio DATE NOT NULL DEFAULT(CURRENT_DATE),
	fecha_fin DATE NOT NULL DEFAULT(CURRENT_DATE + INTERVAL 1 MONTH),
	mes INT NOT NULL DEFAULT(MONTH(CURRENT_DATE)),
	anho INT NOT NULL DEFAULT(YEAR(CURRENT_DATE))
);
CREATE TABLE IF NOT EXISTS presupuesto_gastos(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	tipo INT NOT NULL,
	concepto INT NOT NULL,
	monto DECIMAL(13, 2) NOT NULL,
	presupuesto INT NOT NULL
);
CREATE TABLE IF NOT EXISTS presupuesto_ingresos(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	tipo INT NOT NULL,
	concepto INT NOT NULL,
	monto DECIMAL(13, 2) NOT NULL,
	presupuesto INT NOT NULL
);

